import swaggerUi from "swagger-ui-express";
import { Express } from "express";

import swaggerDocument from "../docs/swagger.json"; // Generated by swagger-autogen by running `node swagger.config.ts`

export const setupSwagger = (app: Express) => {
  app.use("/api/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
};
