import swaggerUi from "swagger-ui-express";
import { Express } from "express";

import swaggerDocument from "../docs/swagger.json"; // Generated by swagger-autogen by running `node src/swagger.config.ts`

export const setupSwagger = (app: Express) => {
  if (process.env.NODE_ENV !== "development") return;
  app.use("/api/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
};
